# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6374006ff4a1cd57b761f1615c1465fbb39cb4ea99db7acc9787e2d24e1d7b8b8b9c1d844c7c9bccb0890bb9e594d0d43d27a1e9db7e65207ddd126b59c0e39b

test:
  secret_key_base: 096ab9b18cffa26cea3db74fd75def375b35d83ed61e46d2ecfead5833a4e7781b67c7bb0195be38b4657b833a093877ea04bcf9918eea2469d1e93cdc2564bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
